// Code generated by umpire-gen; DO NOT EDIT.

package workflow

import (
	"regexp"
	"strconv"
	"strings"
)

// WorkflowFields holds the fields for Workflow availability checks.
type WorkflowFields struct {
	BoundedLoops       []string       `json:"boundedLoops,omitempty"`
	CompositionLimits  map[string]any `json:"compositionLimits,omitempty"`
	DefaultLeasePolicy map[string]any `json:"defaultLeasePolicy,omitempty"`
	DefaultRetryPolicy map[string]any `json:"defaultRetryPolicy,omitempty"`
	EntryNodes         []string       `json:"entryNodes,omitempty"`
	Metadata           map[string]any `json:"metadata,omitempty"`
	Nodes              []string       `json:"nodes,omitempty"`
	SchemaVersion      *float64       `json:"schemaVersion,omitempty"`
	TemplateId         *string        `json:"templateId,omitempty"`
	TemplateVersion    *string        `json:"templateVersion,omitempty"`
	TerminalOutcomes   []string       `json:"terminalOutcomes,omitempty"`
}

// WorkflowConditions holds the conditions for Workflow availability checks.
type WorkflowConditions struct {
}

// WorkflowAvailability holds the availability status for each field.
type WorkflowAvailability struct {
	BoundedLoops       FieldStatus
	CompositionLimits  FieldStatus
	DefaultLeasePolicy FieldStatus
	DefaultRetryPolicy FieldStatus
	EntryNodes         FieldStatus
	Metadata           FieldStatus
	Nodes              FieldStatus
	SchemaVersion      FieldStatus
	TemplateId         FieldStatus
	TemplateVersion    FieldStatus
	TerminalOutcomes   FieldStatus
}

// FieldStatus mirrors the conformance expectedAvailability shape exactly.
// Valid and Error are only populated when a named validator is attached
// to the field and the field is currently enabled and satisfied.
type FieldStatus struct {
	Enabled   bool
	Required  bool
	Satisfied bool
	Fair      bool
	Reason    *string  // nil when enabled; first blocking reason otherwise
	Reasons   []string // all blocking reasons; empty slice when enabled
	Valid     *bool    // nil = no validator; non-nil = validation result
	Error     string   // non-empty only when Valid != nil && !*Valid
}

// contains reports whether a string slice contains a given value.
func contains(s []string, v string) bool {
	for _, ss := range s {
		if ss == v {
			return true
		}
	}
	return false
}
func Check(f WorkflowFields, c WorkflowConditions, prev WorkflowFields) WorkflowAvailability {
	var _ = prev
	return WorkflowAvailability{
		BoundedLoops: FieldStatus{
			Required:  false,
			Enabled:   true,
			Satisfied: len(f.BoundedLoops) > 0,
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		CompositionLimits: FieldStatus{
			Required:  false,
			Enabled:   true,
			Satisfied: len(f.CompositionLimits) > 0,
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		DefaultLeasePolicy: FieldStatus{
			Required:  false,
			Enabled:   true,
			Satisfied: len(f.DefaultLeasePolicy) > 0,
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		DefaultRetryPolicy: FieldStatus{
			Required:  false,
			Enabled:   true,
			Satisfied: len(f.DefaultRetryPolicy) > 0,
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		EntryNodes: FieldStatus{
			Required:  true,
			Enabled:   true,
			Satisfied: len(f.EntryNodes) > 0,
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		Metadata: FieldStatus{
			Required:  false,
			Enabled:   true,
			Satisfied: len(f.Metadata) > 0,
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		Nodes: FieldStatus{
			Required:  true,
			Enabled:   true,
			Satisfied: len(f.Nodes) > 0,
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		SchemaVersion: FieldStatus{
			Required:  true,
			Enabled:   true,
			Satisfied: f.SchemaVersion != nil,
			Fair:      f.SchemaVersion != nil && *f.SchemaVersion == 1,
			Reason: func() *string {
				var reasons []string
				if !(f.SchemaVersion != nil && *f.SchemaVersion == 1) && "workflow schema_version must be 1" != "" {
					reasons = append(reasons, "workflow schema_version must be 1")
				}
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if !(f.SchemaVersion != nil && *f.SchemaVersion == 1) && "workflow schema_version must be 1" != "" {
					reasons = append(reasons, "workflow schema_version must be 1")
				}
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		TemplateId: FieldStatus{
			Required:  true,
			Enabled:   true,
			Satisfied: func() bool { v := f.TemplateId; return v != nil && *v != "" }(),
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		TemplateVersion: FieldStatus{
			Required:  true,
			Enabled:   true,
			Satisfied: func() bool { v := f.TemplateVersion; return v != nil && *v != "" }(),
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		TerminalOutcomes: FieldStatus{
			Required:  true,
			Enabled:   true,
			Satisfied: len(f.TerminalOutcomes) > 0,
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
	}
}

// depSatisfied reports whether a field value is satisfied.
func depSatisfied(f WorkflowFields, name string) bool {
	switch name {
	case "BoundedLoops":
		return len(f.BoundedLoops) > 0
	case "CompositionLimits":
		return len(f.CompositionLimits) > 0
	case "DefaultLeasePolicy":
		return len(f.DefaultLeasePolicy) > 0
	case "DefaultRetryPolicy":
		return len(f.DefaultRetryPolicy) > 0
	case "EntryNodes":
		return len(f.EntryNodes) > 0
	case "Metadata":
		return len(f.Metadata) > 0
	case "Nodes":
		return len(f.Nodes) > 0
	case "SchemaVersion":
		return f.SchemaVersion != nil
	case "TemplateId":
		v := f.TemplateId
		return v != nil && *v != ""
	case "TemplateVersion":
		v := f.TemplateVersion
		return v != nil && *v != ""
	case "TerminalOutcomes":
		return len(f.TerminalOutcomes) > 0
	default:
		return true
	}
}

var emailRegex = regexp.MustCompile(`^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$`)

// isValidEmail checks if a string is a valid email address.
func isValidEmail(s string) bool {
	return emailRegex.MatchString(s)
}

// isValidRegexPattern checks if a string is a valid regex pattern.
func isValidRegexPattern(s, pattern string) bool {
	_, err := regexp.Compile(pattern)
	return err == nil
}

// isValidRegexMatch checks if a string matches a regex pattern.
func isValidRegexMatch(s, pattern string) bool {
	re, err := regexp.Compile(pattern)
	if err != nil {
		return false
	}
	return re.MatchString(s)
}

var urlRegex = regexp.MustCompile(`^https?://[^\s/$.?#].[^\s]*$`)

// isValidURL checks if a string is a valid URL.
func isValidURL(s string) bool {
	return urlRegex.MatchString(s)
}

var integerRegex = regexp.MustCompile(`^-?\d+$`)

// isValidInteger checks if a string represents a valid integer.
func isValidInteger(s string) bool {
	return integerRegex.MatchString(s)
}

var numberRegex = regexp.MustCompile(`^-?\d+(\.\d+)?$`)

// isValidNumber checks if a string represents a valid number.
func isValidNumber(s string) bool {
	return numberRegex.MatchString(s)
}

// parseFloat converts a string to a float64, returning 0 if invalid.
func parseFloat(s string) float64 {
	v, _ := strconv.ParseFloat(s, 64)
	return v
}

// isInRange checks if a string number is within a range spec like "[1,10]".
func isInRange(s, rangeSpec string) bool {
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return false
	}
	r := strings.TrimSpace(rangeSpec)
	if !strings.HasPrefix(r, "[") && !strings.HasPrefix(r, "(") {
		return false
	}
	openInclusive := strings.HasPrefix(r, "[")
	r = strings.TrimPrefix(r, "[")
	r = strings.TrimPrefix(r, "(")
	closeInclusive := strings.HasSuffix(r, "]")
	r = strings.TrimSuffix(r, "]")
	r = strings.TrimSuffix(r, ")")
	parts := strings.Split(r, ",")
	if len(parts) != 2 {
		return false
	}
	lo, err := strconv.ParseFloat(strings.TrimSpace(parts[0]), 64)
	if err != nil {
		return false
	}
	hi, err := strconv.ParseFloat(strings.TrimSpace(parts[1]), 64)
	if err != nil {
		return false
	}
	if openInclusive {
		if v < lo {
			return false
		}
	} else {
		if v <= lo {
			return false
		}
	}
	if closeInclusive {
		if v > hi {
			return false
		}
	} else {
		if v >= hi {
			return false
		}
	}
	return true
}

// RuleMetaEntry holds metadata about a rule for Challenge output.
type RuleMetaEntry struct {
	Field    string
	RuleType string
	Expr     string
	Reason   string
}

// ruleMeta holds metadata about all rules for Challenge output.
var ruleMeta = []RuleMetaEntry{
	{Field: "SchemaVersion", RuleType: "fairWhen", Expr: "f.SchemaVersion != nil && *f.SchemaVersion == 1", Reason: "workflow schema_version must be 1"},
}

// ChallengeResult holds the result of a Challenge call.
type ChallengeResult struct {
	FieldName    string
	Status       FieldStatus
	Explanations []string
}

func Challenge(fieldName string, f WorkflowFields, c WorkflowConditions, prev WorkflowFields) ChallengeResult {
	avail := Check(f, c, prev)
	var status FieldStatus
	var found bool
	var explanations []string
	switch fieldName {
	case "BoundedLoops", "bounded_loops":
		found = true
		status = avail.BoundedLoops
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "CompositionLimits", "composition_limits":
		found = true
		status = avail.CompositionLimits
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "DefaultLeasePolicy", "default_lease_policy":
		found = true
		status = avail.DefaultLeasePolicy
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "DefaultRetryPolicy", "default_retry_policy":
		found = true
		status = avail.DefaultRetryPolicy
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "EntryNodes", "entry_nodes":
		found = true
		status = avail.EntryNodes
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "Metadata", "metadata":
		found = true
		status = avail.Metadata
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "Nodes", "nodes":
		found = true
		status = avail.Nodes
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "SchemaVersion", "schema_version":
		found = true
		status = avail.SchemaVersion
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
		explanations = append(explanations, "* fairWhen: workflow schema_version must be 1")
	case "TemplateId", "template_id":
		found = true
		status = avail.TemplateId
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "TemplateVersion", "template_version":
		found = true
		status = avail.TemplateVersion
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	case "TerminalOutcomes", "terminal_outcomes":
		found = true
		status = avail.TerminalOutcomes
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
	default:
		// Try to find by matching against known field names
		for _, entry := range ruleMeta {
			if entry.Field == fieldName {
				if entry.Reason != "" {
					explanations = append(explanations, "* "+entry.RuleType+": "+entry.Reason)
				}
			}
		}
		if len(explanations) == 0 {
			explanations = []string{"unknown field: " + fieldName}
		}
	}
	if !found {
		return ChallengeResult{FieldName: fieldName, Status: FieldStatus{}, Explanations: explanations}
	}
	return ChallengeResult{FieldName: fieldName, Status: status, Explanations: explanations}
}
