package broker

// AgentMessage is the payload for agent-to-agent channel messages.
// It is used as the payload of "agent_message" control messages pushed
// via SendTo.
//
// The ID, ReplyTo, and ExpectsReply fields support blocking ask/reply
// coordination: the sender sets ExpectsReply=true and a stable ID, the
// receiver replies by sending a new AgentMessage with ReplyTo set to
// the original ID, and the broker routes the reply back to the waiting
// sender via the /wait_reply long-poll endpoint.
type AgentMessage struct {
	// ID is a stable message UUID for deduplication, cancellation, and
	// ask/reply correlation. Generated by the sender; should be unique
	// per sender.
	ID string `json:"id,omitempty"`

	// From is the display name of the sender run (often same as FromRunID).
	From string `json:"from"`

	// FromRunID is the run ID of the sending agent.
	FromRunID string `json:"from_run_id"`

	// ToRunID is the run ID of the intended recipient.
	ToRunID string `json:"to_run_id,omitempty"`

	// Message is the body text.
	Message string `json:"message"`

	// Role is a display label such as "agent", "reviewer", or "supervisor".
	Role string `json:"role,omitempty"`

	// ReplyTo, when non-empty, marks this message as a reply to the
	// original message with the given ID. The broker uses this to match
	// a waiting ask.
	ReplyTo string `json:"reply_to,omitempty"`

	// ExpectsReply, when true, signals that the sender is blocking and
	// expects a reply with ReplyTo pointing back to this message's ID.
	ExpectsReply bool `json:"expects_reply,omitempty"`
}
