// Code generated by umpire-gen; DO NOT EDIT.

package spawnselection

import (
	"regexp"
	"strconv"
	"strings"
)

// SpawnSelectionFields holds the fields for SpawnSelection availability checks.
type SpawnSelectionFields struct {
	Agent       *string `json:"agent,omitempty"`
	Backend     *string `json:"backend,omitempty"`
	Model       *string `json:"model,omitempty"`
	RosterEntry *string `json:"rosterEntry,omitempty"`
	RosterFile  *string `json:"rosterFile,omitempty"`
}

// SpawnSelectionConditions holds the conditions for SpawnSelection availability checks.
type SpawnSelectionConditions struct {
	RosterConfigured bool `json:"rosterConfigured"`
}

// SpawnSelectionAvailability holds the availability status for each field.
type SpawnSelectionAvailability struct {
	Agent       FieldStatus
	Backend     FieldStatus
	Model       FieldStatus
	RosterEntry FieldStatus
	RosterFile  FieldStatus
}

// FieldStatus mirrors the conformance expectedAvailability shape exactly.
// Valid and Error are only populated when a named validator is attached
// to the field and the field is currently enabled and satisfied.
type FieldStatus struct {
	Enabled   bool
	Required  bool
	Satisfied bool
	Fair      bool
	Reason    *string  // nil when enabled; first blocking reason otherwise
	Reasons   []string // all blocking reasons; empty slice when enabled
	Valid     *bool    // nil = no validator; non-nil = validation result
	Error     string   // non-empty only when Valid != nil && !*Valid
}

// contains reports whether a string slice contains a given value.
func contains(s []string, v string) bool {
	for _, ss := range s {
		if ss == v {
			return true
		}
	}
	return false
}
func Check(f SpawnSelectionFields, c SpawnSelectionConditions, prev SpawnSelectionFields) SpawnSelectionAvailability {
	var _ = prev
	return SpawnSelectionAvailability{
		Agent: FieldStatus{
			Required:  false,
			Enabled:   !(f.RosterEntry != nil),
			Satisfied: func() bool { v := f.Agent; return v != nil && *v != "" }(),
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if f.RosterEntry != nil && "direct identity fields are disabled in roster mode" != "" {
					reasons = append(reasons, "direct identity fields are disabled in roster mode")
				}
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if f.RosterEntry != nil && "direct identity fields are disabled in roster mode" != "" {
					reasons = append(reasons, "direct identity fields are disabled in roster mode")
				}
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		Backend: FieldStatus{
			Required:  false,
			Enabled:   !(f.RosterEntry != nil),
			Satisfied: func() bool { v := f.Backend; return v != nil && *v != "" }(),
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if f.RosterEntry != nil && "direct identity fields are disabled in roster mode" != "" {
					reasons = append(reasons, "direct identity fields are disabled in roster mode")
				}
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if f.RosterEntry != nil && "direct identity fields are disabled in roster mode" != "" {
					reasons = append(reasons, "direct identity fields are disabled in roster mode")
				}
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		Model: FieldStatus{
			Required:  false,
			Enabled:   !(f.RosterEntry != nil),
			Satisfied: func() bool { v := f.Model; return v != nil && *v != "" }(),
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if f.RosterEntry != nil && "direct identity fields are disabled in roster mode" != "" {
					reasons = append(reasons, "direct identity fields are disabled in roster mode")
				}
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if f.RosterEntry != nil && "direct identity fields are disabled in roster mode" != "" {
					reasons = append(reasons, "direct identity fields are disabled in roster mode")
				}
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		RosterEntry: FieldStatus{
			Required:  false,
			Enabled:   true,
			Satisfied: func() bool { v := f.RosterEntry; return v != nil && *v != "" }(),
			Fair:      (f.RosterFile != nil || c.RosterConfigured),
			Reason: func() *string {
				var reasons []string
				if !(f.RosterFile != nil || c.RosterConfigured) && "roster_entry requires roster_file unless a roster context is configured" != "" {
					reasons = append(reasons, "roster_entry requires roster_file unless a roster context is configured")
				}
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if !(f.RosterFile != nil || c.RosterConfigured) && "roster_entry requires roster_file unless a roster context is configured" != "" {
					reasons = append(reasons, "roster_entry requires roster_file unless a roster context is configured")
				}
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
		RosterFile: FieldStatus{
			Required:  false,
			Enabled:   ((func() bool { v := f.RosterEntry; return v != nil && *v != "" })() && (f.RosterFile != nil || c.RosterConfigured)),
			Satisfied: func() bool { v := f.RosterFile; return v != nil && *v != "" }(),
			Fair:      true,
			Reason: func() *string {
				var reasons []string
				if !((func() bool { v := f.RosterEntry; return v != nil && *v != "" })() && (f.RosterFile != nil || c.RosterConfigured)) && "roster_file requires roster_entry" != "" {
					reasons = append(reasons, "roster_file requires roster_entry")
				}
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if !((func() bool { v := f.RosterEntry; return v != nil && *v != "" })() && (f.RosterFile != nil || c.RosterConfigured)) && "roster_file requires roster_entry" != "" {
					reasons = append(reasons, "roster_file requires roster_entry")
				}
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: nil,
			Error: "",
		},
	}
}

// depSatisfied reports whether a field value is satisfied.
func depSatisfied(f SpawnSelectionFields, name string) bool {
	switch name {
	case "Agent":
		v := f.Agent
		return v != nil && *v != ""
	case "Backend":
		v := f.Backend
		return v != nil && *v != ""
	case "Model":
		v := f.Model
		return v != nil && *v != ""
	case "RosterEntry":
		v := f.RosterEntry
		return v != nil && *v != ""
	case "RosterFile":
		v := f.RosterFile
		return v != nil && *v != ""
	default:
		return true
	}
}

var emailRegex = regexp.MustCompile(`^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$`)

// isValidEmail checks if a string is a valid email address.
func isValidEmail(s string) bool {
	return emailRegex.MatchString(s)
}

// isValidRegexPattern checks if a string is a valid regex pattern.
func isValidRegexPattern(s, pattern string) bool {
	_, err := regexp.Compile(pattern)
	return err == nil
}

// isValidRegexMatch checks if a string matches a regex pattern.
func isValidRegexMatch(s, pattern string) bool {
	re, err := regexp.Compile(pattern)
	if err != nil {
		return false
	}
	return re.MatchString(s)
}

var urlRegex = regexp.MustCompile(`^https?://[^\s/$.?#].[^\s]*$`)

// isValidURL checks if a string is a valid URL.
func isValidURL(s string) bool {
	return urlRegex.MatchString(s)
}

var integerRegex = regexp.MustCompile(`^-?\d+$`)

// isValidInteger checks if a string represents a valid integer.
func isValidInteger(s string) bool {
	return integerRegex.MatchString(s)
}

var numberRegex = regexp.MustCompile(`^-?\d+(\.\d+)?$`)

// isValidNumber checks if a string represents a valid number.
func isValidNumber(s string) bool {
	return numberRegex.MatchString(s)
}

// parseFloat converts a string to a float64, returning 0 if invalid.
func parseFloat(s string) float64 {
	v, _ := strconv.ParseFloat(s, 64)
	return v
}

// isInRange checks if a string number is within a range spec like "[1,10]".
func isInRange(s, rangeSpec string) bool {
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return false
	}
	r := strings.TrimSpace(rangeSpec)
	if !strings.HasPrefix(r, "[") && !strings.HasPrefix(r, "(") {
		return false
	}
	openInclusive := strings.HasPrefix(r, "[")
	r = strings.TrimPrefix(r, "[")
	r = strings.TrimPrefix(r, "(")
	closeInclusive := strings.HasSuffix(r, "]")
	r = strings.TrimSuffix(r, "]")
	r = strings.TrimSuffix(r, ")")
	parts := strings.Split(r, ",")
	if len(parts) != 2 {
		return false
	}
	lo, err := strconv.ParseFloat(strings.TrimSpace(parts[0]), 64)
	if err != nil {
		return false
	}
	hi, err := strconv.ParseFloat(strings.TrimSpace(parts[1]), 64)
	if err != nil {
		return false
	}
	if openInclusive {
		if v < lo {
			return false
		}
	} else {
		if v <= lo {
			return false
		}
	}
	if closeInclusive {
		if v > hi {
			return false
		}
	} else {
		if v >= hi {
			return false
		}
	}
	return true
}

// RuleMetaEntry holds metadata about a rule for Challenge output.
type RuleMetaEntry struct {
	Field    string
	RuleType string
	Expr     string
	Reason   string
}

// ruleMeta holds metadata about all rules for Challenge output.
var ruleMeta = []RuleMetaEntry{
	{Field: "Agent", RuleType: "disables", Expr: "f.RosterEntry != nil", Reason: "direct identity fields are disabled in roster mode"},
	{Field: "Backend", RuleType: "disables", Expr: "f.RosterEntry != nil", Reason: "direct identity fields are disabled in roster mode"},
	{Field: "Model", RuleType: "disables", Expr: "f.RosterEntry != nil", Reason: "direct identity fields are disabled in roster mode"},
	{Field: "RosterEntry", RuleType: "fairWhen", Expr: "(f.RosterFile != nil || c.RosterConfigured)", Reason: "roster_entry requires roster_file unless a roster context is configured"},
	{Field: "RosterEntry", RuleType: "requires", Expr: "", Reason: "roster_file requires roster_entry"},
}

// ChallengeResult holds the result of a Challenge call.
type ChallengeResult struct {
	FieldName    string
	Status       FieldStatus
	Explanations []string
}

func Challenge(fieldName string, f SpawnSelectionFields, c SpawnSelectionConditions, prev SpawnSelectionFields) ChallengeResult {
	avail := Check(f, c, prev)
	var status FieldStatus
	var found bool
	var explanations []string
	switch fieldName {
	case "Agent", "agent":
		found = true
		status = avail.Agent
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
		explanations = append(explanations, "* disables: direct identity fields are disabled in roster mode")
	case "Backend", "backend":
		found = true
		status = avail.Backend
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
		explanations = append(explanations, "* disables: direct identity fields are disabled in roster mode")
	case "Model", "model":
		found = true
		status = avail.Model
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
		explanations = append(explanations, "* disables: direct identity fields are disabled in roster mode")
	case "RosterEntry", "roster_entry":
		found = true
		status = avail.RosterEntry
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
		explanations = append(explanations, "* fairWhen: roster_entry requires roster_file unless a roster context is configured")
	case "RosterFile", "roster_file":
		found = true
		status = avail.RosterFile
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
		explanations = append(explanations, "* requires RosterEntry: roster_file requires roster_entry")
	default:
		// Try to find by matching against known field names
		for _, entry := range ruleMeta {
			if entry.Field == fieldName {
				if entry.Reason != "" {
					explanations = append(explanations, "* "+entry.RuleType+": "+entry.Reason)
				}
			}
		}
		if len(explanations) == 0 {
			explanations = []string{"unknown field: " + fieldName}
		}
	}
	if !found {
		return ChallengeResult{FieldName: fieldName, Status: FieldStatus{}, Explanations: explanations}
	}
	return ChallengeResult{FieldName: fieldName, Status: status, Explanations: explanations}
}
