// Code generated by umpire-gen; DO NOT EDIT.

package thinkingpolicy

import (
	"regexp"
	"strconv"
	"strings"
)

// ThinkingPolicyFields holds the fields for ThinkingPolicy availability checks.
type ThinkingPolicyFields struct {
	Thinking *string `json:"thinking,omitempty"`
}

// ThinkingPolicyConditions holds the conditions for ThinkingPolicy availability checks.
type ThinkingPolicyConditions struct {
	Backend string `json:"backend"`
	Resume  bool   `json:"resume"`
}

// ThinkingPolicyAvailability holds the availability status for each field.
type ThinkingPolicyAvailability struct {
	Thinking                   FieldStatus
	ActiveThinkingPolicyBranch thinkingPolicyBranch `json:"-"`
}

// FieldStatus mirrors the conformance expectedAvailability shape exactly.
// Valid and Error are only populated when a named validator is attached
// to the field and the field is currently enabled and satisfied.
type FieldStatus struct {
	Enabled   bool
	Required  bool
	Satisfied bool
	Fair      bool
	Reason    *string  // nil when enabled; first blocking reason otherwise
	Reasons   []string // all blocking reasons; empty slice when enabled
	Valid     *bool    // nil = no validator; non-nil = validation result
	Error     string   // non-empty only when Valid != nil && !*Valid
}

// contains reports whether a string slice contains a given value.
func contains(s []string, v string) bool {
	for _, ss := range s {
		if ss == v {
			return true
		}
	}
	return false
}

// thinkingPolicyBranch represents the active branch of the thinkingPolicyBranch oneOf/eitherOf group.
type thinkingPolicyBranch int

const (
	thinkingPolicyBranchNone thinkingPolicyBranch = iota
	Empty                    thinkingPolicyBranch = iota
	FullSupport              thinkingPolicyBranch = iota
	ClaudeStart              thinkingPolicyBranch = iota
)

func Check(f ThinkingPolicyFields, c ThinkingPolicyConditions, prev ThinkingPolicyFields) ThinkingPolicyAvailability {
	var _ = prev
	var thinkingPolicyBranchActive thinkingPolicyBranch = thinkingPolicyBranchNone
	if f.Thinking == nil {
		thinkingPolicyBranchActive = Empty
	}
	if (c.Backend == "codex-app-server" || c.Backend == "pi") && (f.Thinking != nil && *f.Thinking == "off" || f.Thinking != nil && *f.Thinking == "minimal" || f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max") {
		thinkingPolicyBranchActive = FullSupport
	}
	if (c.Backend == "claude" || c.Backend == "claude-channel") && c.Resume == false && (f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max") {
		thinkingPolicyBranchActive = ClaudeStart
	}

	return ThinkingPolicyAvailability{
		Thinking: FieldStatus{
			Required:  false,
			Enabled:   true,
			Satisfied: func() bool { v := f.Thinking; return v != nil && *v != "" }(),
			Fair:      (f.Thinking == nil || ((c.Backend == "codex-app-server" || c.Backend == "pi") && (f.Thinking != nil && *f.Thinking == "off" || f.Thinking != nil && *f.Thinking == "minimal" || f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max")) || ((c.Backend == "claude" || c.Backend == "claude-channel") && c.Resume == false && (f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max"))),
			Reason: func() *string {
				var reasons []string
				if !(f.Thinking == nil) && "thinking is empty (backend default)" != "" {
					reasons = append(reasons, "thinking is empty (backend default)")
				}
				if !((c.Backend == "codex-app-server" || c.Backend == "pi") && (f.Thinking != nil && *f.Thinking == "off" || f.Thinking != nil && *f.Thinking == "minimal" || f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max")) && "codex-app-server and pi support all canonical thinking values on start and resume" != "" {
					reasons = append(reasons, "codex-app-server and pi support all canonical thinking values on start and resume")
				}
				if !((c.Backend == "claude" || c.Backend == "claude-channel") && c.Resume == false && (f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max")) && "claude and claude-channel support low through max only on a new session" != "" {
					reasons = append(reasons, "claude and claude-channel support low through max only on a new session")
				}
				if len(reasons) == 0 {
					return nil
				}
				return &reasons[0]
			}(),
			Reasons: func() []string {
				var reasons []string
				if !(f.Thinking == nil) && "thinking is empty (backend default)" != "" {
					reasons = append(reasons, "thinking is empty (backend default)")
				}
				if !((c.Backend == "codex-app-server" || c.Backend == "pi") && (f.Thinking != nil && *f.Thinking == "off" || f.Thinking != nil && *f.Thinking == "minimal" || f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max")) && "codex-app-server and pi support all canonical thinking values on start and resume" != "" {
					reasons = append(reasons, "codex-app-server and pi support all canonical thinking values on start and resume")
				}
				if !((c.Backend == "claude" || c.Backend == "claude-channel") && c.Resume == false && (f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max")) && "claude and claude-channel support low through max only on a new session" != "" {
					reasons = append(reasons, "claude and claude-channel support low through max only on a new session")
				}
				if reasons == nil {
					reasons = []string{}
				}
				return reasons
			}(),
			Valid: func() *bool {
				v := (f.Thinking != nil && *f.Thinking == "off" || f.Thinking != nil && *f.Thinking == "minimal" || f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max")
				return &v
			}(),
			Error: func() string {
				if f.Thinking != nil && *f.Thinking == "off" || f.Thinking != nil && *f.Thinking == "minimal" || f.Thinking != nil && *f.Thinking == "low" || f.Thinking != nil && *f.Thinking == "medium" || f.Thinking != nil && *f.Thinking == "high" || f.Thinking != nil && *f.Thinking == "xhigh" || f.Thinking != nil && *f.Thinking == "max" {
					return ""
				}
				return "not a canonical thinking value (off, minimal, low, medium, high, xhigh, max)"
			}(),
		},
		ActiveThinkingPolicyBranch: thinkingPolicyBranchActive,
	}
}

// depSatisfied reports whether a field value is satisfied.
func depSatisfied(f ThinkingPolicyFields, name string) bool {
	switch name {
	case "Thinking":
		v := f.Thinking
		return v != nil && *v != ""
	default:
		return true
	}
}

var emailRegex = regexp.MustCompile(`^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$`)

// isValidEmail checks if a string is a valid email address.
func isValidEmail(s string) bool {
	return emailRegex.MatchString(s)
}

// isValidRegexPattern checks if a string is a valid regex pattern.
func isValidRegexPattern(s, pattern string) bool {
	_, err := regexp.Compile(pattern)
	return err == nil
}

// isValidRegexMatch checks if a string matches a regex pattern.
func isValidRegexMatch(s, pattern string) bool {
	re, err := regexp.Compile(pattern)
	if err != nil {
		return false
	}
	return re.MatchString(s)
}

var urlRegex = regexp.MustCompile(`^https?://[^\s/$.?#].[^\s]*$`)

// isValidURL checks if a string is a valid URL.
func isValidURL(s string) bool {
	return urlRegex.MatchString(s)
}

var integerRegex = regexp.MustCompile(`^-?\d+$`)

// isValidInteger checks if a string represents a valid integer.
func isValidInteger(s string) bool {
	return integerRegex.MatchString(s)
}

var numberRegex = regexp.MustCompile(`^-?\d+(\.\d+)?$`)

// isValidNumber checks if a string represents a valid number.
func isValidNumber(s string) bool {
	return numberRegex.MatchString(s)
}

// parseFloat converts a string to a float64, returning 0 if invalid.
func parseFloat(s string) float64 {
	v, _ := strconv.ParseFloat(s, 64)
	return v
}

// isInRange checks if a string number is within a range spec like "[1,10]".
func isInRange(s, rangeSpec string) bool {
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return false
	}
	r := strings.TrimSpace(rangeSpec)
	if !strings.HasPrefix(r, "[") && !strings.HasPrefix(r, "(") {
		return false
	}
	openInclusive := strings.HasPrefix(r, "[")
	r = strings.TrimPrefix(r, "[")
	r = strings.TrimPrefix(r, "(")
	closeInclusive := strings.HasSuffix(r, "]")
	r = strings.TrimSuffix(r, "]")
	r = strings.TrimSuffix(r, ")")
	parts := strings.Split(r, ",")
	if len(parts) != 2 {
		return false
	}
	lo, err := strconv.ParseFloat(strings.TrimSpace(parts[0]), 64)
	if err != nil {
		return false
	}
	hi, err := strconv.ParseFloat(strings.TrimSpace(parts[1]), 64)
	if err != nil {
		return false
	}
	if openInclusive {
		if v < lo {
			return false
		}
	} else {
		if v <= lo {
			return false
		}
	}
	if closeInclusive {
		if v > hi {
			return false
		}
	} else {
		if v >= hi {
			return false
		}
	}
	return true
}

// RuleMetaEntry holds metadata about a rule for Challenge output.
type RuleMetaEntry struct {
	Field    string
	RuleType string
	Expr     string
	Reason   string
}

// ruleMeta holds metadata about all rules for Challenge output.
var ruleMeta = []RuleMetaEntry{
	{Field: "Thinking", RuleType: "check", Expr: "(f.Thinking != nil && *f.Thinking == \"off\" || f.Thinking != nil && *f.Thinking == \"minimal\" || f.Thinking != nil && *f.Thinking == \"low\" || f.Thinking != nil && *f.Thinking == \"medium\" || f.Thinking != nil && *f.Thinking == \"high\" || f.Thinking != nil && *f.Thinking == \"xhigh\" || f.Thinking != nil && *f.Thinking == \"max\")", Reason: "not a canonical thinking value (off, minimal, low, medium, high, xhigh, max)"},
}

// ChallengeResult holds the result of a Challenge call.
type ChallengeResult struct {
	FieldName    string
	Status       FieldStatus
	Explanations []string
}

func Challenge(fieldName string, f ThinkingPolicyFields, c ThinkingPolicyConditions, prev ThinkingPolicyFields) ChallengeResult {
	avail := Check(f, c, prev)
	var status FieldStatus
	var found bool
	var explanations []string
	switch fieldName {
	case "Thinking", "thinking":
		found = true
		status = avail.Thinking
		if status.Reason != nil {
			explanations = append(explanations, "* "+*status.Reason)
		}
		explanations = append(explanations, "* check: not a canonical thinking value (off, minimal, low, medium, high, xhigh, max)")
	default:
		// Try to find by matching against known field names
		for _, entry := range ruleMeta {
			if entry.Field == fieldName {
				if entry.Reason != "" {
					explanations = append(explanations, "* "+entry.RuleType+": "+entry.Reason)
				}
			}
		}
		if len(explanations) == 0 {
			explanations = []string{"unknown field: " + fieldName}
		}
	}
	if !found {
		return ChallengeResult{FieldName: fieldName, Status: FieldStatus{}, Explanations: explanations}
	}
	return ChallengeResult{FieldName: fieldName, Status: status, Explanations: explanations}
}
