// This separate package avoids giving two upstream enums with identical value
// names one invented local enum alias. It shares the agyv115 Go package.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/runtime/agy/interop/v115/snapshot.proto

package agyv115

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotTrajectoryVerbosity int32

const (
	SnapshotTrajectoryVerbosity_CLIENT_TRAJECTORY_VERBOSITY_UNSPECIFIED SnapshotTrajectoryVerbosity = 0
	SnapshotTrajectoryVerbosity_CLIENT_TRAJECTORY_VERBOSITY_DEBUG       SnapshotTrajectoryVerbosity = 1
	SnapshotTrajectoryVerbosity_CLIENT_TRAJECTORY_VERBOSITY_PROD_UI     SnapshotTrajectoryVerbosity = 2
	SnapshotTrajectoryVerbosity_CLIENT_TRAJECTORY_VERBOSITY_FULL        SnapshotTrajectoryVerbosity = 3
)

// Enum value maps for SnapshotTrajectoryVerbosity.
var (
	SnapshotTrajectoryVerbosity_name = map[int32]string{
		0: "CLIENT_TRAJECTORY_VERBOSITY_UNSPECIFIED",
		1: "CLIENT_TRAJECTORY_VERBOSITY_DEBUG",
		2: "CLIENT_TRAJECTORY_VERBOSITY_PROD_UI",
		3: "CLIENT_TRAJECTORY_VERBOSITY_FULL",
	}
	SnapshotTrajectoryVerbosity_value = map[string]int32{
		"CLIENT_TRAJECTORY_VERBOSITY_UNSPECIFIED": 0,
		"CLIENT_TRAJECTORY_VERBOSITY_DEBUG":       1,
		"CLIENT_TRAJECTORY_VERBOSITY_PROD_UI":     2,
		"CLIENT_TRAJECTORY_VERBOSITY_FULL":        3,
	}
)

func (x SnapshotTrajectoryVerbosity) Enum() *SnapshotTrajectoryVerbosity {
	p := new(SnapshotTrajectoryVerbosity)
	*p = x
	return p
}

func (x SnapshotTrajectoryVerbosity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotTrajectoryVerbosity) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_runtime_agy_interop_v115_snapshot_proto_enumTypes[0].Descriptor()
}

func (SnapshotTrajectoryVerbosity) Type() protoreflect.EnumType {
	return &file_internal_runtime_agy_interop_v115_snapshot_proto_enumTypes[0]
}

func (x SnapshotTrajectoryVerbosity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotTrajectoryVerbosity.Descriptor instead.
func (SnapshotTrajectoryVerbosity) EnumDescriptor() ([]byte, []int) {
	return file_internal_runtime_agy_interop_v115_snapshot_proto_rawDescGZIP(), []int{0}
}

var File_internal_runtime_agy_interop_v115_snapshot_proto protoreflect.FileDescriptor

const file_internal_runtime_agy_interop_v115_snapshot_proto_rawDesc = "" +
	"\n" +
	"0internal/runtime/agy/interop/v115/snapshot.proto\x12\x18avenor.agy.v115.snapshot*\xc0\x01\n" +
	"\x1bSnapshotTrajectoryVerbosity\x12+\n" +
	"'CLIENT_TRAJECTORY_VERBOSITY_UNSPECIFIED\x10\x00\x12%\n" +
	"!CLIENT_TRAJECTORY_VERBOSITY_DEBUG\x10\x01\x12'\n" +
	"#CLIENT_TRAJECTORY_VERBOSITY_PROD_UI\x10\x02\x12$\n" +
	" CLIENT_TRAJECTORY_VERBOSITY_FULL\x10\x03BHZFgithub.com/sdougbrown/avenor/internal/runtime/agy/interop/v115;agyv115b\x06proto3"

var (
	file_internal_runtime_agy_interop_v115_snapshot_proto_rawDescOnce sync.Once
	file_internal_runtime_agy_interop_v115_snapshot_proto_rawDescData []byte
)

func file_internal_runtime_agy_interop_v115_snapshot_proto_rawDescGZIP() []byte {
	file_internal_runtime_agy_interop_v115_snapshot_proto_rawDescOnce.Do(func() {
		file_internal_runtime_agy_interop_v115_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_runtime_agy_interop_v115_snapshot_proto_rawDesc), len(file_internal_runtime_agy_interop_v115_snapshot_proto_rawDesc)))
	})
	return file_internal_runtime_agy_interop_v115_snapshot_proto_rawDescData
}

var file_internal_runtime_agy_interop_v115_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_runtime_agy_interop_v115_snapshot_proto_goTypes = []any{
	(SnapshotTrajectoryVerbosity)(0), // 0: avenor.agy.v115.snapshot.SnapshotTrajectoryVerbosity
}
var file_internal_runtime_agy_interop_v115_snapshot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_runtime_agy_interop_v115_snapshot_proto_init() }
func file_internal_runtime_agy_interop_v115_snapshot_proto_init() {
	if File_internal_runtime_agy_interop_v115_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_runtime_agy_interop_v115_snapshot_proto_rawDesc), len(file_internal_runtime_agy_interop_v115_snapshot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_runtime_agy_interop_v115_snapshot_proto_goTypes,
		DependencyIndexes: file_internal_runtime_agy_interop_v115_snapshot_proto_depIdxs,
		EnumInfos:         file_internal_runtime_agy_interop_v115_snapshot_proto_enumTypes,
	}.Build()
	File_internal_runtime_agy_interop_v115_snapshot_proto = out.File
	file_internal_runtime_agy_interop_v115_snapshot_proto_goTypes = nil
	file_internal_runtime_agy_interop_v115_snapshot_proto_depIdxs = nil
}
