name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run Go tests
        run: go test ./...

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install package dependencies
        run: bun install

      - name: Run package builds
        run: bun run build

      - name: Run package tests
        run: bun run test
